const Footer = () => {
  return (
    <footer className="mt-auto py-6 px-8 text-center text-xs text-slate-500 border-t border-slate-900/50">
      <div className="flex flex-col md:flex-row items-center justify-between max-w-7xl mx-auto space-y-2 md:space-y-0">
        <p>&copy; {new Date().getFullYear()} EquiLens. All rights reserved.</p>
        <p className="text-[10px] text-slate-600">
          Disclaimer: Investment research and recommendations generated by AI agents are for informational purposes only. Consult a licensed financial advisor.
        </p>
      </div>
    </footer>
  );
};

export default Footer;
